.TH NDISWRAPPER 8 "April 2006"
.SH NAME
ndiswrapper \- install/modify/remove ndis driver (wrapper)
.SH SYNOPSIS
.B ndiswrapper
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B ndiswrapper
command.
.PP
\fBndiswrapper\fP is a wrapper for the version-specific
\fBndiswrapper-X.X\fP programs (where -X.X is the version number of the
utils; ie, \fBndiswrapper-1.8\fP).  It simply figures out which version
should be called, and calls the appropriate binary.  Each version's man
page contains its usage details.
.SH AUTHOR
This manual page was written by Andres Salomon <dilinger@debian.org>,
for the Debian project (but may be used by others).
