#!/bin/sh

set -e

latest_ndiswrapper () {
	for file in /usr/sbin/ndiswrapper-[\.0-9][\.0-9]*; do
		echo $file
	done | sort -n -t - -k 2 | tail -1
}


NDISWRAPPER=$(latest_ndiswrapper)
if [ -x "$NDISWRAPPER" ]; then
	exec $NDISWRAPPER "$@"
else
	echo "Error: no ndiswrapper utils found!" 1>&2
	exit 1
fi
